name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Racket ${{ matrix.racket-variant }} - ${{ matrix.racket-version }} - ${{ matrix.racket-distribution }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: [ 'current' ]
        racket-variant: [ 'regular', 'CS' ]
        racket-distribution: [ 'full' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v0.10
        with:
          version: ${{ matrix.racket-version }}
          variant: ${{ matrix.racket-variant }}
          distribution: ${{ matrix.racket-distribution }}
      - name: Install package and its dependencies
        run: raco pkg install --auto --batch
      - name: Run tests
        run: raco test -p project-management
